apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lrgx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-lrgx@sha256:01e52c33b3e9bb1d2767e815644c9077e1d0db169ccb44f5d9276a82f4d851ed
        name: my-nodejs
        resources: {}
status: {}
